<a href="https://colab.research.google.com/github/kcastrosm/challenge1-data-science-latam/blob/main/Copia_de_AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

# 1. Análisis de facturación

In [3]:
precio_total_T1 = tienda['Precio'].sum()
precio_total_T1

np.float64(1150880400.0)

In [4]:
precio_total_T2 = tienda2['Precio'].sum()
precio_total_T2

np.float64(1116343500.0)

In [5]:
precio_total_T3 = tienda3['Precio'].sum()
precio_total_T3

np.float64(1098019600.0)

In [6]:
precio_total_T4 = tienda4['Precio'].sum()
precio_total_T4

np.float64(1038375700.0)

# 2. Ventas por categoría

In [14]:
ventas_por_categoria_T1 = tienda.groupby('Categoría del Producto').size().reset_index(name='Ventas')
print('Ventas por categoría en Tienda 1:')
ventas_por_categoria_T1

Ventas por categoría en Tienda 1:

    Categoría del Producto  Ventas
0  Artículos para el hogar     171
1     Deportes y diversión     284
2        Electrodomésticos     312
3             Electrónicos     448
4   Instrumentos musicales     182
5                 Juguetes     324
6                   Libros     173
7                  Muebles     465

In [15]:
ventas_por_categoria_T2 = tienda2.groupby('Categoría del Producto').size().reset_index(name='Ventas')
print('Ventas por categoría en Tienda 2:')
ventas_por_categoria_T2

Ventas por categoría en Tienda 2:

    Categoría del Producto  Ventas
0  Artículos para el hogar     181
1     Deportes y diversión     275
2        Electrodomésticos     305
3             Electrónicos     422
4   Instrumentos musicales     224
5                 Juguetes     313
6                   Libros     197
7                  Muebles     442

In [16]:
ventas_por_categoria_T3 = tienda3.groupby('Categoría del Producto').size().reset_index(name='Ventas')
print('Ventas por categoría en Tienda 3:')
ventas_por_categoria_T3

Ventas por categoría en Tienda 3:

    Categoría del Producto  Ventas
0  Artículos para el hogar     177
1     Deportes y diversión     277
2        Electrodomésticos     278
3             Electrónicos     451
4   Instrumentos musicales     177
5                 Juguetes     315
6                   Libros     185
7                  Muebles     499

In [17]:
ventas_por_categoria_T4 = tienda4.groupby('Categoría del Producto').size().reset_index(name='Ventas')
print('Ventas por categoría en Tienda 4:')
ventas_por_categoria_T4

Ventas por categoría en Tienda 4:

    Categoría del Producto  Ventas
0  Artículos para el hogar     201
1     Deportes y diversión     277
2        Electrodomésticos     254
3             Electrónicos     451
4   Instrumentos musicales     170
5                 Juguetes     338
6                   Libros     187
7                  Muebles     480

# 3. Calificación promedio de la tienda

# 4. Productos más y menos vendidos

# 5. Envío promedio por tienda